// Code generated by MockGen. DO NOT EDIT.
// Source: summarizer.go
//
// Generated by this command:
//
//	mockgen -source=summarizer.go -destination=mock_summarizer.go -package=llm
//

// Package llm is a generated GoMock package.
package llm

import (
	context "context"
	reflect "reflect"

	domain "github.com/YugaAI/PR-Summarizer-CLI/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMSummarizer is a mock of LLMSummarizer interface.
type MockLLMSummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockLLMSummarizerMockRecorder
	isgomock struct{}
}

// MockLLMSummarizerMockRecorder is the mock recorder for MockLLMSummarizer.
type MockLLMSummarizerMockRecorder struct {
	mock *MockLLMSummarizer
}

// NewMockLLMSummarizer creates a new mock instance.
func NewMockLLMSummarizer(ctrl *gomock.Controller) *MockLLMSummarizer {
	mock := &MockLLMSummarizer{ctrl: ctrl}
	mock.recorder = &MockLLMSummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMSummarizer) EXPECT() *MockLLMSummarizerMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockLLMSummarizer) Summarize(ctx context.Context, chunk domain.DiffChunk) (domain.FileSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, chunk)
	ret0, _ := ret[0].(domain.FileSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockLLMSummarizerMockRecorder) Summarize(ctx, chunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockLLMSummarizer)(nil).Summarize), ctx, chunk)
}
